//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _18DemoDisconnected
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dept
    {
        public Dept()
        {
            this.Emps = new HashSet<Emp>();
        }
    
        public int DeptId { get; set; }
        public string DeptName { get; set; }
    
        public virtual ICollection<Emp> Emps { get; set; }
    }
}
