//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _18DemoDisconnected
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp
    {
        public int no { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public int DeptDeptId { get; set; }
    
        public virtual Dept Dept { get; set; }
    }
}
